name: CI Test

on:
  push:
    branches:
      - test
      - prakash-test
  pull_request:
    branches:
      - test
      - prakash-test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["image-classification", "sentiment-analysis"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: AISC2013-Deployment/case_study_2/prakash/${{ matrix.project }}
        run: |
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install -r requirements.txt

      - name: Download NLTK Data
        run: |
          venv/bin/python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords'); nltk.download('wordnet')"

      - name: Run tests
        working-directory: AISC2013-Deployment/case_study_2/prakash/${{ matrix.project }}
        run: |
          venv/bin/python -m unittest test.py
